# Generated by Django 4.2.4 on 2023-08-20 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_data_contratacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
    ]
