# Generated by Django 4.2.4 on 2023-08-18 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_ponto',
            name='hora_entrada_lunch',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 21, 11, 18, 989062)),
        ),
        migrations.AddField(
            model_name='registro_ponto',
            name='hora_fim',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 21, 11, 18, 989062)),
        ),
        migrations.AddField(
            model_name='registro_ponto',
            name='hora_fim_extra',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 21, 11, 18, 989062)),
        ),
        migrations.AddField(
            model_name='registro_ponto',
            name='hora_ini',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 21, 11, 18, 989062)),
        ),
        migrations.AddField(
            model_name='registro_ponto',
            name='hora_ini_extra',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 21, 11, 18, 989062)),
        ),
        migrations.AddField(
            model_name='registro_ponto',
            name='hora_retorno_lunch',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 21, 11, 18, 989062)),
        ),
        migrations.AlterField(
            model_name='registro_ponto',
            name='dia',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 21, 11, 18, 989062)),
        ),
    ]
